# Generated by Django 6.0.2 on 2026-02-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_backgroundtask_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtask',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
